import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const scripts=['AnnualProvisioner','EventSync','SanityCheck'].map(n=>fs.readFileSync(new URL(`../integrations/apps-script/transition-simple/${n}.gs`,import.meta.url),'utf8')).join('\n');
const clone=x=>JSON.parse(JSON.stringify(x));
function harness(){
  const files=new Map(),books=new Map(),forms=new Map(),props=new Map(),triggers=[],writes=[];
  let seq=0,failCopy=false,failAppend=false,actor='asmeohiostate@gmail.com',activeActor='asmeohiostate@gmail.com',locked=false;
  const iter=a=>{let i=0;return {hasNext:()=>i<a.length,next:()=>a[i++]};};
  class Sheet{
    constructor(name,values=[],formulas=[],maxRows=1000){this.name=name;this.values=clone(values);this.formulas=clone(formulas);this.maxRows=maxRows;this.protected=true;this.formUrl=null;}
    getName(){return this.name;} getLastRow(){return Math.max(1,this.values.length);} getMaxRows(){return this.maxRows;} getMaxColumns(){return 20;} getFormUrl(){return this.formUrl;}
    insertRowsAfter(_,n){writes.push('resize');this.maxRows+=n;}
    getProtections(){return this.protected?[{isWarningOnly:()=>this.protected==='warning'}]:[];}
    getDataRange(){return this.getRange(1,1,Math.max(this.values.length,this.formulas.length,1),20);}
    getRange(r,c,n=1,m=1){
      if(typeof r==='string'){const v=/^([A-Z]+)(\d+)$/.exec(r);c=[...v[1]].reduce((a,x)=>a*26+x.charCodeAt(0)-64,0);r=+v[2];}
      const read=grid=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>grid[r+i-1]?.[c+j-1]??''));
      const put=a=>{writes.push(`${this.name}!${r}:${c}`);a.forEach((row,i)=>row.forEach((v,j)=>{(this.values[r+i-1]??=[])[c+j-1]=v;}));if(this.name==='Hub_Settings_Public'&&r>1&&failAppend){failAppend=false;throw Error('append acknowledgement lost');}return range;};
      const range={getValues:()=>read(this.values),getValue:()=>read(this.values)[0][0],getFormulas:()=>read(this.formulas),getFormula:()=>read(this.formulas)[0][0],setValues:put,setValue:v=>put([[v]])};return range;
    }
  }
  class File{
    constructor(id,name,parent,folder=false,mime='sheet'){this.id=id;this.name=name;this.parent=parent;this.folder=folder;this.mime=mime;this.access='private';this.owner='asmeohiostate@gmail.com';this.trashed=false;files.set(id,this);}
    getId(){return this.id;} getName(){return this.name;} getMimeType(){return this.mime;} getOwner(){return {getEmail:()=>this.owner};}getSharingAccess(){return this.access;}isTrashed(){return this.trashed;}
    getEditors(){return this.editors||[];}getViewers(){return this.viewers||[];}getParents(){return iter(this.parent?[files.get(this.parent)]:[]);}getUrl(){return `https://drive.google.com/drive/folders/${this.id}`;}
    getFoldersByName(name){return iter([...files.values()].filter(f=>f.parent===this.id&&f.folder&&f.name===name));}
    getFilesByName(name){return iter([...files.values()].filter(f=>f.parent===this.id&&!f.folder&&f.name===name));}
    createFolder(name){writes.push('create folder');return new File('folder'+ ++seq,name,this.id,true);}
    makeCopy(name,parent){writes.push('copy');const f=new File('copy'+ ++seq,name,parent.id,false,this.mime);
      if(books.has(this.id)){const original=books.get(this.id);books.set(f.id,book(f.id,[...original.sheets.values()].map(s=>{const c=new Sheet(s.name,s.values,s.formulas,s.maxRows);c.protected=s.protected;return c;})));}
      if(forms.has(this.id))forms.set(f.id,form(f.id));
      if(failCopy){failCopy=false;throw Error('copy acknowledgement lost');}return f;
    }
  }
  function book(id,sheets){const b={id,sheets:new Map(sheets.map(s=>[s.name,s])),getId:()=>id,getSheetByName:n=>b.sheets.get(n),getSheets:()=>[...b.sheets.values()],getSpreadsheetTimeZone:()=> 'America/New_York',toast:()=>{}};books.set(id,b);return b;}
  function form(id){const f={id,destination:null,accepting:false,responses:[],choices:[],choiceWrites:0,title:'template',getId:()=>id,getResponses:()=>f.responses,isAcceptingResponses:()=>f.accepting,setAcceptingResponses:v=>{writes.push('intake');f.accepting=v;},setTitle:v=>{writes.push('title');f.title=v;},getDestinationId:()=>{if(!f.destination)throw Error('Exception: The form currently has no response destination.');return f.destination;},setDestination:(_,dest)=>{writes.push('destination');f.destination=dest;const s=new Sheet('Observed response 8',[clone(ctx.ASME_RESPONSE_HEADERS)]);s.formUrl='form:'+id;books.get(dest).sheets.set(s.name,s);},getPublishedUrl:()=>`https://docs.google.com/forms/d/e/${id}/viewform`,getEditUrl:()=>`https://docs.google.com/forms/d/${id}/edit`,getItems:()=>[{getTitle:()=> 'Event ID',asListItem:()=>({getChoices:()=>f.choices.map(c=>({getValue:()=>c})),setChoiceValues:a=>{f.choiceWrites++;writes.push('choices');f.choices=clone(a);}})}]};forms.set(id,f);return f;}
  const ctx=vm.createContext({console,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k)||null,setProperty:(k,v)=>{props.set(k,v);}})},Session:{getEffectiveUser:()=>({getEmail:()=>actor}),getActiveUser:()=>({getEmail:()=>activeActor})},LockService:{getScriptLock:()=>({tryLock:()=>{if(locked)return false;locked=true;return true;},releaseLock:()=>{locked=false;}})},DriveApp:{Access:{PRIVATE:'private'},getFolderById:id=>{const f=files.get(id);if(!f?.folder)throw Error('folder missing');return f;},getFileById:id=>{const f=files.get(id);if(!f||f.folder)throw Error('file missing');return f;}},SpreadsheetApp:{ProtectionType:{SHEET:'sheet'},openById:id=>{if(!books.has(id))throw Error('book missing');return books.get(id);},getActiveSpreadsheet:()=>books.get('annual-master'),flush:()=>{}},FormApp:{DestinationType:{SPREADSHEET:'spreadsheet'},ItemType:{LIST:'list'},openById:id=>{if(!forms.has(id))throw Error('form missing');return forms.get(id);},openByUrl:url=>forms.get(url.slice(5))},Utilities:{sleep:()=>{},parseDate:(date,tz,pattern)=>{assert.equal(tz,'America/New_York');assert.equal(pattern,'yyyy-MM-dd');return date;}},ScriptApp:{EventType:{ON_EDIT:'onEdit'},getProjectTriggers:()=>triggers,newTrigger:handler=>{let id;const b={forSpreadsheet:ss=>{id=ss.getId();return b;},onEdit:()=>b,create:()=>{writes.push('trigger');const t={getHandlerFunction:()=>handler,getTriggerSourceId:()=>id,getEventType:()=> 'onEdit'};triggers.push(t);return t;}};return b;}}});
  vm.runInContext(scripts,ctx);
  new File('root','chapter root',null,true);new File('center','Control Center');
  const settings=new Sheet('Hub_Settings_Public',[clone(ctx.ASME_ANNUAL_HEADERS)]);book('center',[settings]);
  const cfg=new Sheet('Config');[['B2','Fall 2027'],['B3','2027-28'],['B5','TESTING'],['B7','Form Responses 1'],['B17','Event ID']].forEach(([a,v])=>cfg.getRange(a).setValue(v));
  const eventHeaders=['event_id','event_name','event_date','term','academic_year','event_type','points','scoring_active','form_open'];
  const events=new Sheet('Events',[eventHeaders,['20270826-001','Welcome',45000,'Fall 2027','2027-28','General Body Meeting',5,true,true],['closed','Closed',45000,'Fall 2027','2027-28','General Body Meeting',5,true,false]]);
  const sourceSheets=[cfg,new Sheet('_Raw_Ingest',[],[[ctx.ASME_RAW_INGEST_FORMULA]]),events,new Sheet('Roster',[],[["=INDEX('_Raw_Ingest'!C:C,ROW())"]]),new Sheet('Point Log',[],[['=INDEX(_Raw_Ingest!K:K,ROW())']]),new Sheet('Website Staging')];
  for(const [k,id]of Object.entries(ctx.ASME_ANNUAL_TEMPLATES)){new File(id,k,null,false,k==='attendanceForm'?'form':'sheet');if(k==='pointsMaster')book(id,sourceSheets);else if(k==='attendanceForm')form(id);else if(k==='budgetTracker')book(id,[new Sheet('Setup & Lists')]);else book(id,[new Sheet('Config')]);}
  props.set('ANNUAL_PROVISIONER_CONFIG',JSON.stringify({rootFolderId:'root',controlCenterId:'center',engagementGoal:25,calendarIcalUrl:'https://example.org/calendar.ics'}));writes.length=0;
  return {ctx,files,books,forms,props,triggers,writes,settings,Sheet,File,book,form,events,eventHeaders,setActor:v=>{actor=v;},setActiveActor:v=>{activeActor=v;},loseCopy:()=>{failCopy=true;},loseAppend:()=>{failAppend=true;},run:()=>ctx.provisionAnnualYear('2027-2028','Fall 2027'),state:()=>JSON.parse(props.get('ASME_SIMPLE_ANNUAL_2027-2028'))};
}
test('actual provisioner creates five private copies, observed pointer, six dates and exact inactive row',()=>{
  const h=harness(),r=h.run(),s=r.receipt;
  assert.equal(r.success,true);assert.equal(h.writes.filter(x=>x==='copy').length,5);assert.equal(h.writes.filter(x=>x==='create folder').length,6);
  const master=h.books.get(s.ids.pointsMaster),form=h.forms.get(s.ids.attendanceForm);
  assert.equal(form.accepting,false);assert.equal(master.getSheetByName('Config').getRange('B7').getValue(),'Observed response 8');assert.equal(master.getSheetByName('Config').getRange('B16').getValue(),form.id);
  assert.equal(h.books.get(s.ids.pointsExport).getSheetByName('Config').getRange('B1').getValue(),master.id);assert.equal(h.books.get(s.ids.budgetExport).getSheetByName('Config').getRange('B1').getValue(),s.ids.budgetTracker);
  const setup=h.books.get(s.ids.budgetTracker).getSheetByName('Setup & Lists');assert.deepEqual(['B4','B5','B11','B12','B13','B14'].map(a=>setup.getRange(a).getValue()),['2027-08-01','2028-07-31','2027-08-01','2027-12-31','2028-01-01','2028-05-31']);
  assert.equal(h.settings.values[1].length,20);assert.equal(h.settings.values[1][10],false);assert.equal(h.settings.values[1][11],false);assert.equal(h.triggers.length,0);assert.equal(form.choices[0],'20270826-001 - Welcome');
  const before=h.writes.length,stamp=h.settings.values[1][12];h.run();assert.equal(h.writes.length,before);assert.equal(h.settings.values[1][12],stamp);assert.equal(h.settings.values.length,2);
});
test('committed copy with lost acknowledgement resumes without duplicate copies',()=>{const h=harness();h.loseCopy();assert.throws(h.run,/acknowledgement/);assert.equal(h.state().pending.key,'pointsMaster');h.run();assert.equal(h.writes.filter(x=>x==='copy').length,5);assert.equal(h.settings.values.length,2);});
test('committed append with lost acknowledgement reconciles exact draft without duplicate row',()=>{const h=harness();h.loseAppend();assert.throws(h.run,/acknowledgement/);const stamp=h.settings.values[1][12];h.run();assert.equal(h.settings.values.length,2);assert.equal(h.settings.values[1][12],stamp);assert.equal(h.triggers.length,0);});
test('unrelated same-name folder cannot be silently adopted',()=>{const h=harness();new h.File('intruder','ASME 2027-2028','root',true);assert.throws(h.run,/not owned by this run/);assert.equal(h.writes.length,0);});
test('configuration changes and changed inactive draft reject before file mutations',()=>{for(const kind of ['goal','row','active']){const h=harness();h.run();h.writes.length=0;if(kind==='goal'){const cfg=JSON.parse(h.props.get('ANNUAL_PROVISIONER_CONFIG'));cfg.engagementGoal=30;h.props.set('ANNUAL_PROVISIONER_CONFIG',JSON.stringify(cfg));}else h.settings.values[1][kind==='row'?6:10]=kind==='row'?'https://wrong.example':'TRUE';assert.throws(h.run,/configuration changed|no longer matches|active\/current/);assert.equal(h.writes.length,0);}});
test('saved copy identity cannot point at a canonical source or moved copy',()=>{for(const kind of ['source','parent']){const h=harness();h.loseCopy();assert.throws(h.run);const s=h.state();if(kind==='source')s.ids.pointsMaster=h.ctx.ASME_ANNUAL_TEMPLATES.pointsMaster;else{const copied=[...h.files.values()].find(f=>f.name==='2027-2028 Points Master');s.ids.pointsMaster=copied.id;copied.parent='root';}h.props.set('ASME_SIMPLE_ANNUAL_2027-2028',JSON.stringify(s));h.writes.length=0;assert.throws(h.run,/source or control|identity changed/);assert.equal(h.writes.length,0);}});
test('chapter account binding and strict annual year/goal validation',()=>{const h=harness();h.setActor('personal@example.com');assert.throws(h.run,/chapter/);assert.equal(h.writes.length,0);assert.equal(h.ctx.asmeAnnualYear_('2100-2101','Fall 2100').short,'2100-01');assert.equal(h.ctx.asmeAnnualYear_('2199-2200','Fall 2199').end,2200);for(const [y,t]of [['2027-2029','Fall 2027'],['2027-2028','Fall 2028'],['2200-2201','Fall 2200']])assert.throws(()=>h.ctx.asmeAnnualYear_(y,t));assert.throws(()=>h.ctx.asmeAnnualDraftRow_('2027-2028',0,{},'', 'stamp'),/positive/);});
test('events exact headers, eligibility, duplicate IDs and empty placeholders',()=>{const h=harness();assert.deepEqual(clone(h.ctx.asmeEventChoices_(h.events.values)),['20270826-001 - Welcome']);const duplicate=clone(h.events.values);duplicate.push(duplicate[1]);assert.throws(()=>h.ctx.asmeEventChoices_(duplicate),/Duplicate/);const bad=clone(h.events.values);bad[0][0]='wrong';assert.throws(()=>h.ctx.asmeEventChoices_(bad),/headers/);h.run();const master=h.books.get(h.state().ids.pointsMaster),form=h.forms.get(h.state().ids.attendanceForm);master.getSheetByName('Events').values=[h.eventHeaders];h.ctx.asmeSyncEvents_(master);assert.deepEqual(form.choices,['No events currently open for attendance']);const before=form.choiceWrites;h.ctx.asmeSyncEvents_(master);assert.equal(form.choiceWrites,before);assert.equal(form.accepting,false);});
test('event sync refuses mismatched destinations, duplicate questions and source templates',()=>{const h=harness();h.run();const master=h.books.get(h.state().ids.pointsMaster),form=h.forms.get(h.state().ids.attendanceForm),before=form.choiceWrites;form.destination='other';assert.throws(()=>h.ctx.asmeSyncEvents_(master),/destination/);assert.equal(form.choiceWrites,before);form.destination=master.id;const original=form.getItems;form.getItems=()=>[...original(),...original()];assert.throws(()=>h.ctx.asmeSyncEvents_(master),/Exactly one/);assert.throws(()=>h.ctx.asmeSyncEvents_(h.books.get(h.ctx.ASME_ANNUAL_TEMPLATES.pointsMaster)),/canonical/);});
test('edit handler ignores unrelated changes and trigger validation rejects wrong types',()=>{const h=harness();h.run();const master=h.books.get(h.state().ids.pointsMaster);h.ctx.asmeEnsureEventTrigger_(master);h.writes.length=0;h.ctx.asmeEventsEdited({source:master,range:{getSheet:()=>master.getSheetByName('Config'),getRow:()=>2,getNumRows:()=>1,getColumn:()=>1}});assert.equal(h.writes.length,0);h.triggers[0].getEventType=()=> 'onChange';assert.throws(()=>h.ctx.asmeEnsureEventTrigger_(master),/Unexpected/);h.triggers[0].getEventType=()=> 'onEdit';h.ctx.asmeEnsureEventTrigger_(master);assert.equal(h.triggers.length,1);});
test('preflight accepts native quoted/unquoted proxy refs but leaves actual scoring manual',()=>{const h=harness();h.run();const master=h.books.get(h.state().ids.pointsMaster),before=h.writes.length,report=clone(h.ctx.asmeSanityReport_(master));assert.equal(report.filter(r=>!r.manual).every(r=>r.pass),true,JSON.stringify(report));assert.equal(report.at(-1).manual,true);assert.equal(report.at(-1).pass,false);assert.equal(h.writes.length,before);});
test('preflight detects warning-only protection, renamed response refs, public output and open intake',()=>{const h=harness();h.run();const master=h.books.get(h.state().ids.pointsMaster),form=h.forms.get(h.state().ids.attendanceForm);master.getSheetByName('_Raw_Ingest').protected='warning';master.getSheetByName('Roster').formulas[0].push("=INDEX('Observed response 8'!C:C,2)");master.getSheetByName('Website Staging').values=[[],['Private person']];form.accepting=true;const failures=clone(h.ctx.asmeSanityReport_(master)).filter(r=>!r.pass).map(r=>r.test);for(const label of ['Protected raw proxy uses exact Config pointer','Roster and Point Log use only stable proxy references','Public member output suppressed','Form intake closed for pre-flight'])assert.ok(failures.includes(label));});

test('private access cannot hide explicitly shared external viewers',()=>{const h=harness();h.files.get('root').viewers=[{getEmail:()=> 'external@example.com'}];assert.throws(h.run,/private chapter-owned/);assert.equal(h.writes.length,0);});
test('copied response schema failure prevents Config updates and settings append',()=>{const h=harness();h.loseCopy();assert.throws(h.run);// Alter the copied Form link result before setup can update Config.
  const source=h.files.get(h.ctx.ASME_ANNUAL_TEMPLATES.attendanceForm),copy=source.makeCopy.bind(source);source.makeCopy=(...args)=>{const f=copy(...args),form=h.forms.get(f.id),link=form.setDestination;form.setDestination=(...a)=>{link(...a);const sheet=h.books.get(a[1]).getSheetByName('Observed response 8');sheet.values[0][0]='Wrong';};return f;};
  assert.throws(h.run,/exact twelve headers/);const state=h.state(),config=h.books.get(state.ids.pointsMaster).getSheetByName('Config');assert.equal(config.getRange('B7').getValue(),'Form Responses 1');assert.equal(h.settings.values.length,1);});
test('preflight cannot certify an unrelated lookalike response tab',()=>{const h=harness();h.run();const master=h.books.get(h.state().ids.pointsMaster);master.getSheetByName('Observed response 8').formUrl=null;const result=clone(h.ctx.asmeSanityReport_(master)).find(r=>r.test==='Response tab and exact twelve headers');assert.equal(result.pass,false);});
test('failed event sync releases manual lock and leaves trigger uninstalled',()=>{const h=harness();const master=h.book('annual-master',[new h.Sheet('Config'),h.events]);master.getSheetByName('Config').getRange('B16').setValue('wrong');master.getSheetByName('Config').getRange('B17').setValue('Event ID');assert.throws(()=>h.ctx.installEventSyncTrigger(),/form missing/);assert.equal(h.triggers.length,0);const f=h.form('wrong');f.destination='annual-master';assert.equal(h.ctx.installEventSyncTrigger().events,1);assert.equal(h.triggers.length,1);h.ctx.installEventSyncTrigger();assert.equal(h.triggers.length,1);});

test('malformed saved receipt rejects without creating copies',()=>{const h=harness();h.loseCopy();assert.throws(h.run);const s=h.state();s.ids='corrupt';h.props.set('ASME_SIMPLE_ANNUAL_2027-2028',JSON.stringify(s));h.writes.length=0;assert.throws(h.run,/saved receipt is invalid/);assert.equal(h.writes.length,0);});

test('closed-row duplicate IDs and string checkbox values cannot silently corrupt dropdown eligibility',()=>{const h=harness(),rows=clone(h.events.values);rows.push([...rows[1].slice(0,7),false,false]);assert.throws(()=>h.ctx.asmeEventChoices_(rows),/Duplicate event ID/);const invalid=clone(h.events.values);invalid[1][7]='TRUE';assert.throws(()=>h.ctx.asmeEventChoices_(invalid),/boolean checkboxes/);});

test('one-argument UI route and fixed editor entry require no per-year target property',()=>{const h=harness();assert.equal(h.props.has('ANNUAL_PROVISIONER_TARGET'),false);assert.equal(h.ctx.provision2027_2028().success,true);assert.equal(h.ctx.provisionReviewedAnnualYear('2027-2028').success,true);assert.throws(()=>h.ctx.provisionReviewedAnnualYear('2027-2029'),/consecutive/);assert.equal(h.settings.values.length,2);});

test('execute-as-owner invocation still refuses another active account or unknown active identity',()=>{for(const account of ['personal@example.com','']){const h=harness();h.setActiveActor(account);assert.throws(()=>h.ctx.provisionReviewedAnnualYear('2027-2028'),/chapter/);assert.equal(h.writes.length,0);}});
